AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure of EC2 instances using cloudformation
Resources:
  server-1-security-group:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for server-1
      VpcId: vpc-03aedb1c6857fc0ad
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  server-1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678
      InstanceType: t2.micro
      KeyName: server-1-key-pair
      SecurityGroups:
        - Ref: server-1-security-group
      Tags:
        - Key: Name
          Value: server-1
        - Key: Environment
          Value: Test
  